pipeline {
    /* insert Declarative Pipeline here */

    //Specify agent
    agent any

    stages {
        stage('Build with unit test') {
        steps {
            sh 'mvn clean install'
          }
        }
    }
}