pipeline {
    /* insert Declarative Pipeline here */

    //Specify agent
    agent any

    stages {
        stage('Build with unit test') {
        steps {
            dir("${env.WORKSPACE}/spring-boot-docker-jenkins") {
                sh 'mvn clean install'
            }
          }
        }
    }
}