pipeline {
    /* insert Declarative Pipeline here */

    //Specify agent
    agent any

    stages {
        stage('Maven Build with unit test') {
            steps {
                dir("${env.WORKSPACE}/spring-boot-docker-jenkins") {
                    sh 'mvn clean install'
                }
              }
        }

        stage('Docker build spring-boot image') {
            steps {
                dir("${env.WORKSPACE}/spring-boot-docker-jenkins/docker") {
                    sh 'docker build -t spring-boot/greetings .'
                }
            }
        }

        stage('Run Docker container ') {
            steps {
                dir("${env.WORKSPACE}/spring-boot-docker-jenkins/docker") {
                    sh 'docker run -p 5000:8080 spring-boot/greetings'
                }
            }
        }
    }
}